# Automation of the Fake rate method workflow
#
# Author: Evan K. Friis, Christian Veelken (UC Davis)

# Define your numerator and denominator and HLT selection.  
# Note you have to escape the $!!
HLT = " \$$hltJet15U > 0.5 "
# for background estimation in EWK tau analysis
##DEN = " \$$jetPt > 20. & abs(\$$jetEta) < 2.1 & \$$probe > 0.5 & \$$byLeadTrackFinding > 0.5 & \$$byLeadTrackPtCut > 0.5"
##NUM = " \$$byTaNCfrQuarterPercent > 0.5"
# for reproducing ICHEP results
DEN = " \$$jetPt > 10. & abs(\$$jetEta) < 2.5 & \$$probe > 0.5"
NUM = " \$$byTaNCfrHalfPercent > 0.5"
#ALGO = patPFTausDijetTagAndProbeShrinkingCone
ALGO = shrinking
DIR = TancFakeRate
XML = fakeRateMVADef.xml
SAMPLE = data

# Train the MVA
${DIR}/fakeRate.db: ${XML} ${DIR}/pass.root ${DIR}/fail.root 
	mkdir -p train
	rm -f $@.temp.db
	./trainTauFakeRate_cfg.py xml=fakeRateMVADef.xml passing=${DIR}/pass.root \
	  failing=${DIR}/fail.root outputFile=$@.temp.db
	mv $@.temp.db $@

# Build the 'numerator'
${DIR}/pass.root: fakeratemethod_ntuplize.py samples.py samples_cache.py 
	mkdir -p ${DIR}
	./fakeratemethod_ntuplize.py -passing --ntuple ${ALGO} --hlt ${HLT} \
	  --num ${NUM} --den ${DEN} --sample ${SAMPLE} --output $@ 

# Build the 'denominator'
${DIR}/fail.root: fakeratemethod_ntuplize.py samples.py samples_cache.py 
	mkdir -p ${DIR}
	./fakeratemethod_ntuplize.py -failing --ntuple ${ALGO} --hlt ${HLT} \
	  --num ${NUM} --den ${DEN} --sample ${SAMPLE} --output $@
